name: Build branch

on:
  pull_request:
    branches:
      - '**'
      - '!release/*'

jobs:
  install-and-build:
    name: Install & Build
    runs-on: blacksmith-2vcpu-ubuntu-2204
    env:
      NODE_OPTIONS: '--max-old-space-size=6144'
    outputs:
      frontend_changed: ${{ steps.paths-filter.outputs.frontend == 'true' }}
      non_python_changed: ${{ steps.paths-filter.outputs.non-python == 'true' }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Check for frontend changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: paths-filter
        with:
          filters: |
            frontend:
              - packages/frontend/**
              - packages/@n8n/design-system/**
              - packages/@n8n/chat/**
              - packages/@n8n/codemirror-lang/**
              - .bundlemonrc.json
              - .github/workflows/ci-pull-requests.yml
            non-python:
              - '**'
              - '!packages/@n8n/task-runner-python/**'
      - name: Setup and Build
        if: steps.paths-filter.outputs.non-python == 'true'
        uses: n8n-io/n8n/.github/actions/setup-nodejs-blacksmith@f5fbbbe0a28a886451c886cac6b49192a39b0eea # v1.104.1

      - name: Run format check
        if: steps.paths-filter.outputs.non-python == 'true'
        run: pnpm format:check

      - name: Run typecheck
        if: steps.paths-filter.outputs.non-python == 'true'
        run: pnpm typecheck

      - name: Upload Frontend Build Artifacts
        if: steps.paths-filter.outputs.frontend == 'true'
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: frontend-build-artifacts
          path: |
            packages/frontend/dist/
            packages/@n8n/design-system/dist/
            packages/@n8n/chat/dist/
          retention-days: 1